services:
  app-engine:
    build: .
    environment:
      - SERVICE_TYPE=server
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - RESOURCE_FOLDER=resources
      - SERVER_BIND=*
      - SERVER_PORT=8080
    ports:
      - "8888:8080"
    depends_on:
      - redis

  world-server:
    build: .
    environment:
      - SERVICE_TYPE=wServer
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - RESOURCE_FOLDER=resources
      - SERVER_BIND=0.0.0.0
      - SERVER_PORT=2050
    ports:
      - "2050:2050"
      - "2051:2051"
    depends_on:
      - redis

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
